services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: haseera-app
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "127.0.0.1:8000:8080"

    volumes:
      - ./storage:/app/storage

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    container_name: haseera-db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    volumes:
      - haseera_mysql:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  haseera_mysql:
